language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
    - php: 7.1

before_install:
  - composer self-update

install: composer update --prefer-dist --no-interaction

script:
  - vendor/bin/phpspec run
  - vendor/bin/phpcs --standard=PSR2 src
